server {
    listen 8443 ssl http2;
    include /etc/nginx/includes/listen-ipv6-ssl.conf;

    include /etc/nginx/includes/real-ip.conf;
    include /etc/nginx/includes/server-ssl.conf;
    include /etc/nginx/includes/server-common.conf;
}
