version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github_actions"

  - package-ecosystem: "docker"
    directories:
      - "/Dockerfiles/agent/*"
      - "/Dockerfiles/agent2/*"
      - "/Dockerfiles/build-base/*"
      - "/Dockerfiles/build-mysql/*"
      - "/Dockerfiles/build-pgsql/*"
      - "/Dockerfiles/build-sqlite3/*"
      - "/Dockerfiles/java-gateway/*"
      - "/Dockerfiles/proxy-mysql/*"
      - "/Dockerfiles/proxy-sqlite3/*"
      - "/Dockerfiles/server-mysql/*"
      - "/Dockerfiles/server-pgsql/*"
      - "/Dockerfiles/snmptraps/*"
      - "/Dockerfiles/web-apache-mysql/*"
      - "/Dockerfiles/web-apache-pgsql/*"
      - "/Dockerfiles/web-nginx-mysql/*"
      - "/Dockerfiles/web-nginx-pgsql/*"
      - "/Dockerfiles/web-service/*"
    schedule:
      interval: "weekly"
      time: "06:30"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-images:
        applies-to: version-updates
        patterns:
          - "*"
        group-by: dependency-name
