repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              ^env_vars/\.MYSQL$|
              ^env_vars/\.POSTGRES$
          )

      - id: trailing-whitespace
        exclude: |
          (?x)(
              .*\.patch$
          )

      - id: check-yaml
        args: [--allow-multiple-documents]

      - id: check-symlinks
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--format, parsable]
