#!/usr/bin/env bash
set -e

docker_process_sql --database=mysql <<-EOSQL
CREATE ROLE IF NOT EXISTS '${ZBX_SERVER_DB_ROLE}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, CREATE TEMPORARY TABLES, TRIGGER, REFERENCES
  ON \`${ZBX_SERVER_DB_NAME}\`.*
  TO '${ZBX_SERVER_DB_ROLE}';

CREATE ROLE IF NOT EXISTS '${ZBX_WEB_DB_ROLE}';
GRANT SELECT, INSERT, UPDATE, DELETE
  ON \`${ZBX_SERVER_DB_NAME}\`.*
  TO '${ZBX_WEB_DB_ROLE}';

FLUSH PRIVILEGES;
EOSQL
