#!/usr/bin/env bash
set -e

docker_process_sql --database=mysql <<-EOSQL
CREATE ROLE IF NOT EXISTS '${ZBX_PROXY_DB_ROLE}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, CREATE TEMPORARY TABLES, TRIGGER, REFERENCES
  ON \`${ZBX_PROXY_DB_NAME}\`.*
  TO '${ZBX_PROXY_DB_ROLE}';

FLUSH PRIVILEGES;
EOSQL
