#!/usr/bin/env bash
set -e

docker_process_sql --database=mysql <<-EOSQL
CREATE USER IF NOT EXISTS '${ZBX_SERVER_DB_USER}'@'${ZBX_SERVER_DB_USER_HOST}'
  $(identified_by_sql "$ZBX_SERVER_DB_PASSWORD_SQL");
GRANT '${ZBX_SERVER_DB_ROLE}' TO '${ZBX_SERVER_DB_USER}'@'${ZBX_SERVER_DB_USER_HOST}';
$(default_role_sql "$ZBX_SERVER_DB_ROLE" "$ZBX_SERVER_DB_USER" "$ZBX_SERVER_DB_USER_HOST")

CREATE USER IF NOT EXISTS '${ZBX_WEB_DB_USER}'@'${ZBX_WEB_DB_USER_HOST}'
  $(identified_by_sql "$ZBX_WEB_DB_PASSWORD_SQL");
GRANT '${ZBX_WEB_DB_ROLE}' TO '${ZBX_WEB_DB_USER}'@'${ZBX_WEB_DB_USER_HOST}';
$(default_role_sql "$ZBX_WEB_DB_ROLE" "$ZBX_WEB_DB_USER" "$ZBX_WEB_DB_USER_HOST")

FLUSH PRIVILEGES;
EOSQL
