### Option: HistoryProvider
#	Configuration of history storage provider using format <provider>[;<options>] where:
#		<provider> - one of supported configuration providers - sql (default), elasticsearch, clickhouse.
#		<options> - comma delimited key=value pairs. Values can be quoted.
#	Options:
#	ClickHouse:
#		url,username,password,db,log_slow_queries,value_types,source_ip,precache,
#		ssl_cert_file,ssl_key_file,ssl_key_password,ssl_verify_peer,ssl_verify_host,ssl_ca_location,ssl_cert_location,ssl_key_location
#	Elasticsearch:
#		url,log_slow_queries,value_types,source_ip,date_index,precache
#	sql:
#		value_types,precache
#	Examples:
#	ClickHouse:
#		HistoryProvider=clickhouse;value_types="uint,dbl,str,log,text,json",url=http://localhost:8123,db=zabbix,username=zabbix,password=zabbix
#	Elasticsearch:
#		HistoryProvider=elasticsearch;value_types="uint,dbl,str,log,text,json",url=http://localhost:9200,date_index=0
#	ClickHouse and Elasticsearch:
#		HistoryProvider=clickhouse;value_types="uint,dbl,str",url=http://localhost:8123,db=zabbix,username=zabbix,password=zabbix
#		HistoryProvider=elasticsearch;value_types="log,text,json",url=http://localhost:9200,date_index=0
#
# Mandatory: no
# Default:
# HistoryProvider=
