### Option: TelemetryProvider
#	Configuration of telemetry data source using format <provider>[;<options>] where:
#		<provider> - one of supported telemetry data sources - clickhouse.
#		<options> - comma delimited key=value pairs. Values can be quoted.
#	Options:
#	ClickHouse:
#		url,username,password,db,source_ip,vault_path,
#		ssl_cert_file,ssl_key_file,ssl_key_password,ssl_verify_peer,ssl_verify_host,ssl_ca_location,ssl_cert_location,ssl_key_location
#
# Mandatory: no
# Default:
# TelemetryProvider=
