####### Bridge-adapter #######
#

### Option: EnableMobileDevices
#	Enable mobile device support on Zabbix server.
#		0 - disable
#		1 - enable
#
# Mandatory: no
# Default:
# EnableMobileDevices=0

EnableMobileDevices=${ZBX_ENABLEMOBILEDEVICES}

### Option: BridgeAdapterURL
#	Bridge Adapter HTTP[S] URL.
#	Example: https://bridge-adapter.example.com:10005/rpc
#
# Mandatory: no
# Default:
# BridgeAdapterURL=

BridgeAdapterURL=${ZBX_BRIDGEADAPTERURL}

### Option: BridgeAdapterConnectTo
#	Connect to the specified host and port instead of the host and port from BridgeAdapterURL.
#	Format: <host>:<port>
#	Example: 127.0.0.1:18080
#
# Mandatory: no
# Default:
# BridgeAdapterConnectTo=

BridgeAdapterConnectTo=${ZBX_BRIDGEADAPTERCONNECTTO}
