# A list of listening addresses, on which to receive incoming SNMP notifications
snmpTrapdAddr udp:1162
snmpTrapdAddr udp6:1162

# Do not fork from the calling shell
doNotFork yes
# File in which to store the process ID of the notification receiver
pidFile /tmp/snmptrapd.pid
# Disables support for the NOTIFICATION-LOG-MIB
#doNotRetainNotificationLogs yes

authCommunity log,execute,net public
disableAuthorization yes
ignoreAuthFailure yes

# Specify the format used for trap handle location
#format execute %B\n%b\n%V\n%v\n

# o - Log messages to the standard output stream.
# logOption o

# Invokes the specified program (with the given arguments) whenever a notification
# is received that matches the OID token
traphandle default /bin/bash /usr/sbin/zabbix_trap_handler.sh
