- name: Clean Up Disk Space
  if: runner.os == 'Linux'
  run: |
    # Space usage before cleanup
    df -h /
 
#    # Remove unused tool caches (comment any required ones with #)
#    sudo rm -rf /usr/lib/jvm
#    sudo rm -rf /usr/local/.ghcup
#    sudo rm -rf /usr/local/lib/android
#    sudo rm -rf /usr/local/share/powershell
#    sudo rm -rf /usr/share/dotnet
#    sudo rm -rf /usr/share/swift
#    sudo rm -rf "$AGENT_TOOLSDIRECTORY"
 
    # Verify gains
    df -h /
